name: release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: nodejs 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm ci
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
            @ebuckleyk:registry=https://npm.pkg.github.com/
          EOF
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create or publish release pr to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
